version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build:
      context:
        angular-container # specify the directory of the Dockerfile
    volumes:
        - "./angular-container/src:/usr/src/app/src"
    ports:
      - "4200:4200" # specify port forewarding

  express: #name of the second service
    # docker run --name plusminusexpress -p 3000:3000 -v $PWD:/usr/src/app plusminusexpress:dev
    build: express-container # specify the directory of the Dockerfile
    volumes:
        - "./express-container:/usr/src/app"
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
